baseURL: "https://blog.simon-hu.org/"
title: Simon's Blog
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Simon's Blog
  description: "So, you found me. Welcome to my blog. I am a software engineer who works at OPC IT Pty Limited. I am responsible for the daily maintenance and development of Drupal websites at my workplace, and in this blog I write about programming, technology, and other things that I learn during my professional journey. You can find me via the following..."
  keywords: [Blog, Portfolio, PaperMod]
  author: "Suowei Hu"
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false
  hideFooter: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Simon's Blog"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Simon's Blog"
    subtitle: "So, you found me. Welcome to my blog. I am a software engineer who works at OPC IT Pty Limited. I am responsible for the daily maintenance and development of Drupal websites at my workplace, and in this blog I write about programming, technology, and other things that I learn during my professional journey. You can find me via the following..."
    imageUrl: "/android-chrome-512x512.png"
    imageWidth: 150
    imageHeight: 150
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "So, you found me. Welcome to my blog. I am a software engineer who works at OPC IT Pty Limited. I am responsible for the daily maintenance and development of Drupal websites at my workplace, and in this blog I write about programming, technology, and other things that I learn during my professional journey. You can find me via the following..."
  socialIcons:
    - name: github
      url: "https://github.com/"
    - name: linkedin
      url: "https://www.linkedin.com/in/suowei-hu-0249b0181/"
    - name: email
      url: "mailto:suowei.h@gmail.com"
    - name: cv
      url: "/resume"
    - name: medium
      url: "https://suowei-hu.medium.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/SuoweiHu/SuoweiHu.github.io/content"
    Text: "Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: archives
    #   name: Archive
    #   url: /archives/
    #   weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    # - identifier: series
    #   name: Series
    #   url: /series/
    #   weight: 20
    # - identifier: time
    #   name: Time
    #   url: /times/
    #   weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 90
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    guessSyntax: true
    lineNos: true
    # style: monokai
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
taxonomies:
  category: categories
  tag: tags
  series: series